# Generated by Django 2.1.3 on 2018-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_cources',
            name='Fee_Structure',
            field=models.IntegerField(blank=True),
        ),
    ]
