# Generated by Django 2.1.3 on 2018-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_commentbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbox',
            name='Comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='commentbox',
            name='Date_time',
            field=models.DateTimeField(default=''),
        ),
    ]
