# Generated by Django 2.1.3 on 2018-12-01 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181201_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentbox',
            name='Name',
        ),
        migrations.AlterField(
            model_name='commentbox',
            name='Comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='commentbox',
            name='Date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
