# Generated by Django 2.1.3 on 2018-12-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181201_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentbox',
            name='Date_time',
        ),
    ]
