# Generated by Django 2.1.3 on 2018-12-01 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_commentbox_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbox',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
