# Generated by Django 2.1.3 on 2020-04-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_commentbox_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sarpanch_Name_Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
