# Generated by Django 2.1.3 on 2020-04-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sarpanch_name_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarpanch_name_pic',
            name='image',
            field=models.FileField(upload_to='foo-pictures'),
        ),
    ]
