# Generated by Django 2.1.3 on 2020-04-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200405_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarpanch_name_pic',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
