# Generated by Django 2.1.3 on 2020-04-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200407_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_pics_article',
            name='base_admin_name',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='home_page_pics_article',
            name='base_admin_pic',
            field=models.FileField(default='0000000', upload_to=''),
        ),
        migrations.AddField(
            model_name='home_page_pics_article',
            name='best_article',
            field=models.TextField(default='0000000', max_length=500),
        ),
        migrations.AddField(
            model_name='home_page_pics_article',
            name='home_fixed_image',
            field=models.FileField(default='0000000', upload_to=''),
        ),
    ]
