# Generated by Django 2.1.3 on 2020-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200407_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='base_admin_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='base_admin_pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='best_article',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='home_dynamic_images',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='home_fixed_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
