# Generated by Django 2.1.3 on 2020-04-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200407_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='base_admin_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='home_dynamic_images',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='home_fixed_image',
            field=models.FileField(upload_to=''),
        ),
    ]
