# Generated by Django 2.1.3 on 2020-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200407_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarpanch_name_pic',
            name='Mobile_Number',
            field=models.IntegerField(blank=True, default='34'),
            preserve_default=False,
        ),
    ]
