# Generated by Django 2.1.3 on 2020-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_sarpanch_name_pic_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarpanch_name_pic',
            name='Mobile_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sarpanch_name_pic',
            name='full_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='sarpanch_name_pic',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
