# Generated by Django 2.1.3 on 2020-04-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200407_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page_pics_article',
            name='best_article',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
