# Generated by Django 2.1.3 on 2020-04-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
