# Generated by Django 2.1.3 on 2020-04-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
