# Generated by Django 2.1.3 on 2020-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200412_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_year', models.FileField(upload_to='School/')),
                ('name_of_student', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=100)),
                ('mentor_name', models.CharField(max_length=100)),
                ('mobile_Number', models.IntegerField(null=True)),
                ('notice', models.CharField(max_length=100)),
            ],
        ),
    ]
