# Generated by Django 2.1.3 on 2020-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_school_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=100)),
                ('mobile_Number', models.IntegerField(null=True)),
                ('notice', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='school_data',
            name='mentor_name',
        ),
        migrations.RemoveField(
            model_name='school_data',
            name='mobile_Number',
        ),
        migrations.RemoveField(
            model_name='school_data',
            name='notice',
        ),
    ]
