# Generated by Django 2.1.3 on 2020-04-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200419_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='running_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('explanation', models.TextField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
