# Generated by Django 2.1.3 on 2020-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_running_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Father_Name', models.CharField(max_length=500)),
                ('Village', models.CharField(max_length=500)),
                ('Mobile_Number', models.IntegerField(blank=True)),
                ('Message', models.TextField(max_length=150)),
            ],
        ),
    ]
