# Generated by Django 2.1.3 on 2020-04-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_social_notice_user_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_notice',
            old_name='Notice',
            new_name='public_notice',
        ),
    ]
