# Generated by Django 2.1.3 on 2020-04-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200421_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='social_notice',
            new_name='social_notice_data',
        ),
    ]
