# Generated by Django 2.1.3 on 2020-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200421_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_form',
            name='Message',
            field=models.CharField(max_length=150),
        ),
    ]
