# Generated by Django 2.1.3 on 2020-04-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200421_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentbox',
        ),
        migrations.DeleteModel(
            name='list_of_cources',
        ),
    ]
